from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Classroom', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=50, unique=True)), ('capacity', models.PositiveIntegerField(help_text='Number of student seats'))]),
        migrations.CreateModel(name='ExamSchedule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('date', models.DateField()), ('slot', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=10)), ('start_time', models.TimeField()), ('end_time', models.TimeField())], options={'ordering': ['date', 'slot']}),
        migrations.CreateModel(name='Faculty', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100)), ('email', models.EmailField(blank=True, max_length=254)), ('designation', models.CharField(choices=[('PROF', 'Professor'), ('ASSOC', 'Associate Professor'), ('ASSIST', 'Assistant Professor')], max_length=10)), ('duty_quota', models.PositiveIntegerField(default=10))]),
        migrations.CreateModel(name='PhDScholar', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100)), ('duty_quota', models.PositiveIntegerField(default=12))]),
        migrations.CreateModel(name='DutyAllocation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('role_type', models.CharField(choices=[('PROF', 'Professor'), ('ASSIST', 'Assistant Professor'), ('PHD', 'PhD Scholar')], max_length=10)), ('detained_round', models.CharField(choices=[('NONE', 'None'), ('DOUBT', 'Round 1 - Doubt'), ('QP', 'Round 2 - Question Paper Shortage')], default='NONE', max_length=10)), ('created_at', models.DateTimeField(auto_now_add=True)), ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_allocations', to='allocation.classroom')), ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_allocations', to='allocation.examschedule')), ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_allocations', to='allocation.faculty')), ('phd_scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_allocations', to='allocation.phdscholar'))], options={'unique_together': {('exam_schedule', 'classroom', 'faculty', 'phd_scholar')}}),
        migrations.CreateModel(name='UFMRecord', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('count', models.PositiveIntegerField(default=1)), ('notes', models.TextField(blank=True)), ('created_at', models.DateTimeField(default=django.utils.timezone.now)), ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufm_records', to='allocation.examschedule')), ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.faculty')), ('phd_scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.phdscholar'))]),
    ]
