# Generated by Django 5.2.12 on 2026-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phdscholar',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
