# Generated by Django 5.2.12 on 2026-10-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_faculty_must_change_password_and_more'),
        ('allocation', '0004_seating_roll_numbers_per_section'),
    ]

    operations = [
    ]
