# Generated by Django 5.2.12 on 2026-10-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_merge_20261008_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='must_change_password',
        ),
        migrations.RemoveField(
            model_name='phdscholar',
            name='must_change_password',
        ),
    ]
